package com.example.todo

enum class Screens {
    HOME_SCREEN,
    SIGN_UP_SCREEN,
    SIGN_IN_SCREEN,
    TASK_SCREEN,
    OPEN_SCREEN,
    ADD_TASK_SCREEN,
    NOTIFICATION_SCREEN,
    COMPLETED_TASK_SCREEN,
    DELAY_TASK_SCREEN,
    USER_PROFILE_SCREEN,
    RECOVERY_SCREEN
}